### ISSUE TITLE
Updating dependencies

### ISSUE THREAD

**Issue by JoseeWouters** [markteekman/accessible-astro-starter#102]
I noticed some dependencies are outdated, like the version of eslint that is used is deprecated. Are you planning on updating this?

**Comment by markteekman** [comment]
Hey @JoseeWouters (of zal ik zeggen hallo 😄),

I've actually recently announced that I've finally got more time and resources to invest into the Accessible Astro projects, so updating dependencies alongside shipping new features is all part of the plan 😊 I'm making a roadmap as we speak (https://github.com/users/markteekman/projects/1?pane=info) and I'll add this one to the list!

Thanks!

**Comment by markteekman** [comment]
@JoseeWouters dependencies have been updated to the latest stable version in #103 🙂
