### ISSUE TITLE
Feature: Dynamically apply aria-current to active page

### ISSUE THREAD

**Issue by djmtype** [markteekman/accessible-astro-starter#20]
Currently, `aria-current` is hardcoded and is only applied to the Home page link. The navigation would need retooling so `aria-current` is applied to the currently viewed page.

**Comment by markteekman** [comment]
Ah yes, nicely spotted @djmtype! I'll add this functionality in a future update, along with two extra demo pages as an example for how `aria-current` works 🙂

**Comment by djmtype** [comment]
@markteekman This is a cheap example that works: 

```
<li><a href="/" aria-current={Astro.request.url.pathname === '/' ? 'page' : undefined}>Home</a></li>
<li><a href="/about" aria-current={Astro.request.url.pathname === '/about' ? 'page' : undefined}>About</a></li>
<-- etc.  -->
```

But maybe there's a way that integrates better with your setup.  
Otherwise, splitting out the Navigation items into a JSON file might be better for client management with Netlify CMS, for example, then loop through the list.

**Comment by markteekman** [comment]
Thanks for the suggestion @djmtype! I like the creativity of this solution 🙂 I think I'll ultimately use a click event listener on the `<ul>` element and change the `aria-current` attribute depending on which link is clicked. Nevertheless, that idea about setting the items in a JSON file is a really good one too! Maybe one for a future update, as I'm thinking of moving the `Navigation.astro` component to the [accessible-astro-components](https://github.com/markteekman/accessible-astro-components) package eventually.

**Comment by markteekman** [comment]
Added in https://github.com/markteekman/accessible-astro-starter/releases/tag/v1.2.4, thanks again for the suggestion @djmtype 🙂
