### ISSUE TITLE
what is svgo in the adtro config?

### ISSUE THREAD

**Issue by SteveALee** [markteekman/accessible-astro-starter#41]
The inclusion of [svgo in the vite config](https://github.com/markteekman/accessible-astro-starter/blob/main/astro.config.mjs#L7) doesn't seem to be needed and I can find no documentation on what it might be.

**Comment by markteekman** [comment]
Hey @SteveALee, thanks for submitting the issue! Good question, it's there because this starter template ships with the [Astro Icon](https://github.com/natemoo-re/astro-icon/) by default. The icon package can be used in combination with the Notification component from the [Accessible Astro Components](https://github.com/markteekman/accessible-astro-components) package for example. I had to add this to the config to make the icon package work, as they state in their readme. Although, the issue which is being mentioned there (https://github.com/natemoo-re/astro-icon/issues/2) now seems to say it would no longer be necessary with the newer versions of Astro, so I'll be sure to try it out and see if it works without the added config. If so, I'll remove it 😄

**Comment by SteveALee** [comment]
I was having errors with another theme's use of astro-icon and that led me to that package's readme where I spotted the reference. Dunno why Google let me down.

I got impression it's purely optimisation but it gets my vote for most poorly documented config :)

Adding it to other project didn't fix my problem though and it wasn't that referenced issue #2.

Thanks.

**Comment by pyrossh** [comment]
I'm using astro v1.3.1 on node v16.16.0
It works in dev without the vite config change but in build step it doesn't work even with the vite config change, using ssr cloudflare pages adapter.
```js
✘ [ERROR] Could not resolve "os"

    node_modules/svgo/lib/svgo-node.js:3:19:
      3 │ const os = require('os');
        ╵                    ~~~~

  The package "os" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "fs"

    node_modules/svgo/lib/svgo-node.js:4:19:
      4 │ const fs = require('fs');
        ╵                    ~~~~

  The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "url"

    node_modules/svgo/lib/svgo-node.js:5:34:
      5 │ const { pathToFileURL } = require('url');
        ╵                                   ~~~~~

  The package "url" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    node_modules/svgo/lib/svgo-node.js:6:21:
      6 │ const path = require('path');
        │                      ~~~~~~
        ╵                      "./path"

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

 error   Build failed with 4 errors:
  node_modules/svgo/lib/svgo-node.js:3:19: ERROR: Could not resolve "os"
  node_modules/svgo/lib/svgo-node.js:4:19: ERROR: Could not resolve "fs"
  node_modules/svgo/lib/svgo-node.js:5:34: ERROR: Could not resolve "url"
  node_modules/svgo/lib/svgo-node.js:6:21: ERROR: Could not resolve "path"
  File:
    node_modules/svgo/lib/svgo-node.js
  Code:
    > 3 | const os = require('os');
        |                   ^
      4 | const fs = require('fs');
      5 | const { pathToFileURL } = require('url');
      6 | const path = require('path');

  Stacktrace:
Error: Build failed with 4 errors:
node_modules/svgo/lib/svgo-node.js:3:19: ERROR: Could not resolve "os"
node_modules/svgo/lib/svgo-node.js:4:19: ERROR: Could not resolve "fs"
node_modules/svgo/lib/svgo-node.js:5:34: ERROR: Could not resolve "url"
node_modules/svgo/lib/svgo-node.js:6:21: ERROR: Could not resolve "path"
```

Any ideas why this happens?

**Comment by markteekman** [comment]
Just tested it myself and it seems that this can be removed from the theme so I'll do so in the next update 🙂 Thanks again @SteveALee!
