### ISSUE TITLE
Accordion component looks weird when in use

### ISSUE THREAD

**Issue by codiini** [markteekman/accessible-astro-starter#42]
I followed the same instructions to install and use the components, however; the `Accordion` and `AccordionItem` components look a bit weird when I use them on my page:

<img width="830" alt="Screenshot 2022-10-04 at 18 04 00" src="https://user-images.githubusercontent.com/57962747/193882480-bb09d29b-247a-427f-a9e2-c20f21a899ac.png">

Any idea how this could be fixed?

**Comment by markteekman** [comment]
Hi @codiini, thanks for submitting the issue! Could you provide some extra information on the issue:

- Are you using the Accessible Astro Starter theme or a different theme?
- What browser / OS did you use, does it happen in other browsers too?
- Can you provide a link to a reproduction of the bug so I can inspect it?

Thanks! 😊

**Comment by markteekman** [comment]
@codiini closing this for now, but let me now if you still need help with it!
