### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by verlanmar** [markteekman/accessible-astro-starter#44]
Hi!

Would love to see the internationalization support, please.

Example implementation in Astro:

https://docs.astro.build

https://github.com/withastro/astro/tree/main/examples/docs

Thank you!

**Comment by markteekman** [comment]
Hey @verlanmar,

That's a great idea! It would really add some extra value to the theme. However, there are currently some other priorities on the roadmap that need to be considered first (the biggest one being the https://www.accessible-astro.dev/ documentation website). For now it's beyond the scope of this project but it is added to the idea list! 

In the meantime though I would definitely recommend checking out @yassinedoghri awesome https://github.com/yassinedoghri/astro-i18next package and see if you can integrate that with your theme 🙂

**Comment by markteekman** [comment]
@verlanmar closing this for now since there is good third party support. It's on a list for considered features in the future. Thanks again!
