### ISSUE TITLE
Sub Menu Z-Index on Desktop

### ISSUE THREAD

**Issue by yohuck** [markteekman/accessible-astro-starter#46]
The sub menu z-index is set to 0 on desktop so it doesn't inherit the menu z-index of 100 and displays underneath components like the cards. 

In the chrome developer tools it can be debugged by switching off the z-index: 0:

#main-navigation.is-desktop .desktop-menu {
    visibility: visible;
    z-index: 0;
    position: static;
}

![Untitled_ Nov 4, 2022 11_17 PM](https://user-images.githubusercontent.com/99624222/200102565-7096ac29-41e2-4c73-9eab-802f7d83e686.gif)

**Comment by markteekman** [comment]
Good one @yohuck! Hadn't spotted it yet 🤔 Thanks for submitting!

**Comment by yohuck** [comment]
@markteekman I'm happy to work it if you'd like!

**Comment by markteekman** [comment]
Sure @yohuck! I appreciate the help 😊

**Comment by yohuck** [comment]
@markteekman made PR https://github.com/markteekman/accessible-astro-starter/pull/47. LMK if you need anything else!

**Comment by markteekman** [comment]
Thanks a lot @yohuck! Merged and updated the release, thanks for your help. Let me know if you find anything else 🙂
