### ISSUE TITLE
Support for Astro 2?

### ISSUE THREAD

**Issue by Neurrone** [markteekman/accessible-astro-starter#50]
Hey, I'm a new user to Astro, which just recently had its v2 release.

Wondering if it would be possible to update this theme to support v2?

**Comment by markteekman** [comment]
Hey @Neurrone! A great suggestion! I'm actually working on a v2 of this theme at the moment (with new components, redesigned landing page, Tailwind support and more) that also includes Astro v2 🙂 For now though you could simply remove and `npm install astro@latest` in the project to use the latest version right away.

**Comment by markteekman** [comment]
Added in the latest update, thanks for your patience @Neurrone!
