### ISSUE TITLE
Page layout appears zoomed

### ISSUE THREAD

**Issue by sangramrath** [markteekman/accessible-astro-starter#60]
Hello Mark, 
I have an issue where the page layout appears zoomed (compared to the demo website). I have attached screenshots. The space around the page is less in the local run.

I am cloning the repo and run it without any modifications at the moment (I am exploring if it would fit my use case).
I compared a few things and everything is stock, such as padding, grid layout and spacing etc.

It may be something very basic, hence I appreciate your time for this.

**Demo Website Screenshot 1**
<img width="1437" alt="Screenshot-of-demo-website-1" src="https://user-images.githubusercontent.com/6134395/236662021-8da3a256-46ae-44c3-9296-7a2a968cbfea.png">
<br>
**Local Run Screenshot 1**
<img width="1437" alt="Screenshot-of-local-run-1" src="https://user-images.githubusercontent.com/6134395/236662032-654cc5d1-a64f-4882-bea1-3a8d8b5142d9.png">
<br>
**Demo Website Screenshot 2**
<img width="1436" alt="Screenshot-of-demo-website-2" src="https://user-images.githubusercontent.com/6134395/236661754-35da8aa8-a5ce-4ecf-b29a-2252abae0844.png">
<br>
**Local Run Screenshot 2**
<img width="1435" alt="Screenshot-of-local-run-2" src="https://user-images.githubusercontent.com/6134395/236661756-1ca0a71c-61d2-4811-bdb1-b7f17753e81f.png">

**Comment by markteekman** [comment]
Hi @sangramrath! Hmm, that's a very weird issue and hard for me to reproduce. When I run my local setup it looks exactly like the demo. What browser / OS are you using? And does this still apply when you run `npm run build` and upload the `/dist` to some server?

**Comment by fayazmiraz** [comment]
> Hello Mark, I have an issue where the page layout appears zoomed 

Just to be absolutely sure that there's no silly mistake here: Can you please press Ctrl+0 (on Windows/Linux) or CMD+0 (on mac) on both the local and the web version?

Browsers tend to remember the last zoom setting based on the URL. It's possible that one of those URL is zoomed out or zoomed in.

**Comment by markteekman** [comment]
@sangramrath I see there's indeed a difference, as mentioned in the linked issue above. I'll look into a solution when I can make some time.

**Comment by markteekman** [comment]
Solved in #76, thanks @saulopaiva!

**Comment by sangramrath** [comment]
Hello @markteekman thank you. I was travelling over the last few months and wasn't actively monitoring my notifications.
Also thank you @saulopaiva for the commit and @fayazmiraz.
