### ISSUE TITLE
A simple install and run, does not work

### ISSUE THREAD

**Issue by miguelgargallo** [markteekman/accessible-astro-starter#71]
mgarg@pylarpc MINGW64 /d/gh/Astro0/accessible-astro-starter (main)
$ npm install
 WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
Packages: +745
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: D:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 767, reused 630, downloaded 115, added 745, done
node_modules/.pnpm/sharp@0.32.4/node_modules/sharp: Running install scnode_modules/.pnpm/sharp@0.32.4/node_modules/sharp: Running install script, done in 2.3s

devDependencies:
+ @astrojs/mdx 0.19.7
+ @astrojs/partytown 1.0.3 (1.2.3 is available)
+ @astrojs/tailwind 3.0.0 (4.0.0 is available)
+ @typescript-eslint/eslint-plugin 5.50.0 (6.4.0 is available)        
+ @typescript-eslint/parser 5.50.0 (6.4.0 is available)
+ accessible-astro-components 2.1.0 (2.1.3 is available)
+ astro 2.0.1 (2.10.13 is available)
+ astro-compress 2.0.6 (2.0.14 is available)
+ astro-icon 0.7.3 (0.8.1 is available)
+ eslint 8.33.0 (8.47.0 is available)
+ eslint-plugin-astro 0.23.0 (0.29.0 is available)
+ eslint-plugin-jsx-a11y 6.7.1
+ prettier 2.8.3 (3.0.2 is available)
+ prettier-plugin-astro 0.8.0 (0.12.0 is available)
+ prettier-plugin-tailwindcss 0.2.2 (0.4.1 is available)
+ sass 1.49.9 (1.64.2 is available)
+ svgo 2.8.0 (3.0.2 is available)
+ tailwindcss 3.2.7 (3.3.3 is available)

 WARN  Issues with peer dependencies found
.
└─┬ @astrojs/mdx 0.19.7
  └─┬ @astrojs/markdown-remark 2.2.1
    └── ✕ unmet peer astro@^2.5.0: found 2.0.1

The integrity of 2679 files was checked. This might have caused installation to take longer.
Done in 13.4s

mgarg@pylarpc MINGW64 /d/gh/Astro0/accessible-astro-starter (main)    
$ npm run dev

> accessible-astro-starter@2.0.6 dev D:\gh\Astro0\accessible-astro-starter
> astro dev

 error   addContentEntryType is not a function
  File:
    D:\gh\Astro0\accessible-astro-starter\node_modules\.pnpm\@astrojs+mdx@0.19.7_astro@2.0.1\node_modules\@astrojs\mdx\dist\index.js:18:9   
  Code:
    17 |         addPageExtension(".mdx");
    > 18 |         addContentEntryType({
         |         ^
      19 |           extensions: [".mdx"],
      20 |           async getEntryInfo({ fileUrl, contents }) {      
      21 |             const parsed = parseFrontmatter(contents, fileURLToPath(fileUrl));
  Stacktrace:
TypeError: addContentEntryType is not a function
    at astro:config:setup (file:///D:/gh/Astro0/accessible-astro-starter/node_modules/.pnpm/@astrojs+mdx@0.19.7_astro@2.0.1/node_modules/@astrojs/mdx/dist/index.js:18:9)
    at async withTakingALongTimeMsg (file:///D:/gh/Astro0/accessible-astro-starter/node_modules/.pnpm/astro@2.0.1_sass@1.49.9/node_modules/astro/dist/integrations/index.js:15:18)
    at async runHookConfigSetup (file:///D:/gh/Astro0/accessible-astro-starter/node_modules/.pnpm/astro@2.0.1_sass@1.49.9/node_modules/astro/dist/integrations/index.js:69:7)
    at async createContainer (file:///D:/gh/Astro0/accessible-astro-starter/node_modules/.pnpm/astro@2.0.1_sass@1.49.9/node_modules/astro/dist/core/dev/container.js:31:14)
    at async createContainerWithAutomaticRestart (file:///D:/gh/Astro0/accessible-astro-starter/node_modules/.pnpm/astro@2.0.1_sass@1.49.9/node_modules/astro/dist/core/dev/restart.js:90:28)
    at async dev (file:///D:/gh/Astro0/accessible-astro-starter/node_modules/.pnpm/astro@2.0.1_sass@1.49.9/node_modules/astro/dist/core/dev/dev.js:10:19)
    at async runCommand (file:///D:/gh/Astro0/accessible-astro-starter/node_modules/.pnpm/astro@2.0.1_sass@1.49.9/node_modules/astro/dist/cli/index.js:141:7)
    at async cli (file:///D:/gh/Astro0/accessible-astro-starter/node_modules/.pnpm/astro@2.0.1_sass@1.49.9/node_modules/astro/dist/cli/index.js:180:5)

 ELIFECYCLE  Command failed with exit code 1.

**Comment by markteekman** [comment]
@miguelgargallo just tried a fresh download and `npm i && npm run dev` and it works fine, so I'm not sure what's happening on your end. Are you perhaps using pnpm as your package manager? Looking at this line: `Content-addressable store is at: D:.pnpm-store\v3`

**Comment by miguelgargallo** [comment]
letme try, if so, my apologies. wait a min

**Comment by miguelgargallo** [comment]
@markteekman, My apologies:

```
Hello, . today is, Fri, Aug 25, 2023 12:01:24 PM
> npm i
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

added 771 packages, and audited 772 packages in 1m

313 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
> npm run dev

> accessible-astro-starter@2.0.6 dev
> astro dev

   astro  v2.10.14 started in 2734ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  

```

It was completly my fault, cause I want to contyribute on another thing from the code I saw, and I was not able to deploy, for labs,

Thanks

**Comment by markteekman** [comment]
@miguelgargallo no problem, glad it works! 😊
