### ISSUE TITLE
Main navigation accessibility improvement

### ISSUE THREAD

**Issue by markteekman** [markteekman/accessible-astro-starter#79]
- [X] Openend dropdown menu should close when the users tabs out of it (on desktop)
- [x] ~The mobile menu should trap the focus when it's openend~
- [x] ~Optional: open menu items on hover (with a slight closing delay)~
- [x] ~Optional: provide an extra menu item which is a link and as well has a dropdown~

Examples:
- https://codepen.io/markteekman/pen/vYvbpmE
- https://codepen.io/markteekman/pen/OJrdQZw

**Comment by gsi-kevincarrera** [comment]
Hi, I am working on these, but i do not have push access to make a pr, may you help me with it?

**Comment by markteekman** [comment]
Hey @gsi-kevincarrera, thanks for contributing to the project, it's highly appreciated 😊 I did see a PR so I figured you've got that part worked out now? I'll have a look at it when I have the time 😄
