### ISSUE TITLE
Update navigation bar reference during window resize

### ISSUE THREAD

**Issue by gsi-kevincarrera** [markteekman/accessible-astro-starter#86]
This issue pertains to the navigation bar’s unordered list (ul) reference not being updated in the code when the window size is reduced and the view switches to mobile.

Currently, the ul reference of the navigation bar is stored when the page is loaded. However, when the window size is decreased and the view changes to mobile, this ul reference is not updated in the code. This could lead to inconsistencies in the navigation bar’s behavior and appearance between desktop and mobile views.  Solving this would help to solve another open issue, about trapping the focus on mobile view

**Comment by gsi-kevincarrera** [comment]
Just figured out, maybe it is not a good idea to update the same mainMenu instance, due to the event listeners. Better create another set of functions if needed to manage mobile view

**Comment by gsi-kevincarrera** [comment]
Just figured out, maybe it is not a good idea to update the same mainMenu instance, but create another set of functions, with another event listener if needed, to manage mobile view. A feedback will be great in order to choose a path

**Comment by markteekman** [comment]
Hey @gsi-kevincarrera, thanks for taking the time to submit this issue! I'll take a look at it when I've got the time to verify what's happening and I'll get back to you then!

**Comment by markteekman** [comment]
@gsi-kevincarrera I don't know whether it matters that the `ul` reference isn't updated on resize, since the menu doesn't dynamically change? If the menu would have an extra item on another page it would require a page reload and set a new reference. Or did you mean something else?

**Comment by gsi-kevincarrera** [comment]
Opened this issue, due to some inconvinients, when working on the 'mobile menu traps focus' issue. But I figured out a way, as you can see in the PR, I think this issue can be closed

**Comment by markteekman** [comment]
Ah, I understand! Alright, I'll close this one up. Thanks!
