### ISSUE TITLE
astro build fails with memory allocation error

### ISSUE THREAD

**Issue by fi-ma** [markteekman/accessible-astro-starter#92]
Trying the new version 3.1.2, which unfortunately fails on me every time I am running `npm run build`:
```shell
> accessible-astro-starter@3.1.2 build
> astro build

21:53:52 [build] output: "static"
21:53:52 [build] directory: <dir>
21:53:52 [build] Collecting build info...
21:53:52 [build] ✓ Completed in 1.11s.
21:53:52 [build] Building static entrypoints...
21:53:59 [astro-icon] Loaded icons from ion, mdi
memory allocation of 86603180 bytes failed
```

I did not touch anything, simply cloned the repo and ran the build command.

The previous version, 3.1.1, builds without issues for me.

I am running Windows 11 22H2, npm version 10.3.0, node version v20.11.0.

**Comment by markteekman** [comment]
Hey @fi-ma! Hmm, that's weird. I tried it and the build run worked locally and the automatic build/deploy on Netlify also worked 🤔 Stupid suggestion maybe, but did you run `npm install` before running `npm run build`?

**Comment by fi-ma** [comment]
Hi @markteekman!
That's weird, I was running it previously from PowerShell (7.4.0) - that's where I was getting the memory allocation error like the one above.
Just tried the Windows cmd instead and it builds!

Btw. the previous version, 3.1.1, builds without issues from PS.

Anyways, thanks!

**Comment by markteekman** [comment]
That's odd 😅 It might be due to more resources being needed since Astro Icon has changed a bit? Anyway, glad it works now!
