### ISSUE TITLE
dark mode default

### ISSUE THREAD

**Issue by alexucgit** [markteekman/accessible-astro-starter#94]
How can I make sure that dark mode is set as default?

**Comment by markteekman** [comment]
Hey @alexucgit! There's currently no option for that, but I can see that be something you'd want to set. It's best to submit an issue for this feature in https://github.com/markteekman/accessible-astro-components 🙂

**Comment by markteekman** [comment]
@alexucgit it took some time to get there but the option is finally available if you upgrade your `accessible-astro-components` package to the latest version:

```jsx
---
import { DarkMode } from 'accessible-astro-components'
---
<!-- Uses system preferences by default -->
<DarkMode />

<!-- Forces dark mode on first visit -->
<DarkMode initialMode="dark" />

<!-- Forces light mode on first visit -->
<DarkMode initialMode="light" />
```

#103
