### ISSUE TITLE
CloseModal is not defined

### ISSUE THREAD

**Issue by Ryusse** [markteekman/accessible-astro-starter#97]
Hi, I just cloned the template and in the button to close the modal with the function “closeModal()” I get this error:
![Captura de pantalla 2024-07-25 224252](https://github.com/user-attachments/assets/487485c9-6a0f-417c-bac2-f446a9d2be77)

![Captura de pantalla 2024-07-25 225022](https://github.com/user-attachments/assets/d3cf9864-dc3b-4598-a2c8-a6cb908110d4)

**Comment by markteekman** [comment]
Hey @Ryusse, thanks for submitting the issue! I checked and I'm not getting the error, neither locally nor in production. Have you changed anything since you cloned the repository?

**Comment by markteekman** [comment]
@Ryusse should be solved now in the latest update to the Accessible Astro Package :)

**Comment by Ryusse** [comment]
Thank you so much, sorry for the late reply. I love your work!!

**Comment by Ryusse** [comment]
Thank you so much, sorry for the late reply.
